// src/infrastructure/components/Cart/ProductCard.vue
<template>
  <div v-if="Product" class="p-4 h-40 max-w-lg border rounded flex product__cart">
    <div class="w-2/5 flex items-center image">
      <img class="w-full h-fit m-auto" :src="Product.pictures[0]" alt="Image " />
    </div>
    <div class="w-2/5 flex flex-col description">
      <span
        class="font-bold text-black w-full h-14 overflow-hidden text-ellipsis line-clamp name"
      >
        {{ Product.name }}
      </span>
      <div class="price">
        <div class="flex gap-2 discount">
          <span class="text-gray-500 line-through"> ${{ Product.price }} </span>
          <span
            class="text-white rounded bg-black px-2 h-6 flex items-center justify-center text-xs"
          >
            {{ Product.discount }}% OFF
          </span>
        </div>
        <span class="text-black font-bold"> ${{ discount }} </span>
      </div>

      <buttons :id="Product.id"/>
       
    </div>
    <div class="w-1/5 flex flex-col justify-start items-end delete">
      <div @click="deleteProduct" class="w-5 h-fit cursor-pointer icon">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 14 17"
          class="sc-iWFTwQ imHBBB"
        >
          <path
            d="M13.664 1.819H9.482V0H4.23v1.819H.05v3.32h1.59v9.752c0 .997.817 1.807 1.821 1.807h6.792c1.004 0 1.822-.81 1.822-1.807V5.14h1.59V1.82zM5.038.8h3.636V1.82H5.038V.8zm6.228 14.09c0 .555-.455 1.006-1.014 1.006H3.46c-.559 0-1.014-.451-1.014-1.006V5.14h8.82v9.752zm1.59-10.553h-12V2.62h12v1.718z"
            transform="translate(-328 -133) translate(328 133)"
          ></path>
        </svg>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, ref, watchEffect } from "vue";
import API from "../../netwotk/client";
import { useShoppingStore } from "../../stores/ShoppingStore";
import { ProductAPI } from "../interfaces/Product";
import Buttons from "./Buttons.vue";
export default {
  components: { Buttons },
  name: "ProductCard",
  props: {
    id: {
      required: true,
      type: String,
    },
    quantity: {
      required: true,
      type: Number,
    },
  },
  setup(props) {
    const ShoppingStore = useShoppingStore();
    let Product = ref<ProductAPI>();

    const getProductById = async () => {
      let productSearched = await API.product.productById(props.id);

      if (productSearched) {
        Product.value = productSearched;
      }
    };

    const addToCart = () => {
      ShoppingStore.addProduct(props.id);
    };
    const deleteOneProduct = () => {
      ShoppingStore.deleteOneProduct(props.id);
    };
    const deleteProduct = () => {
      ShoppingStore.deleteProduct(props.id);
    };

    const discount = computed(() => {
      if (Product.value) {
        let { price, discount } = Product.value;
        let priceUpdated = price - (discount * price) / 100;
        return priceUpdated;
      }
      return 0;
    });

    watchEffect(async () => {
      await getProductById();
    });

    return {
      Product,
      deleteProduct,
      discount,
    };
  },
};
</script>

// src/components/Cards/ProductCardComponent.tsx
import { Link } from "react-router-dom";
import { ProductInterface } from "../../interfaces/ProductInterface";

interface ProductCardProps {
  addToCart: (id:number) => void;
  data: ProductInterface;
}

const ProductCardComponent = ({ data, addToCart }: ProductCardProps) => {
  const { discount, code, fees, id, name, pictures } = data;
  return (
    <div className="p-4 border rounded-xl card__product">
      <div className="flex justify-between discount__plans">
        <div className=" rounded-2xl flex items-center font-bold text-white bg-[#2189FF] h-8 px-3 discounts">
          -{discount}%
        </div>
        <div className="flex flex-col items-center border rounded-md shadow-md plans">
          <span className="pt-1 text-xs font-bold leading-none">hasta</span>
          <span className="leading-none text-[#2189FF] text-4xl font-bold">
            {fees}
          </span>
          <span className="leading-none  pb-1 text-[#2189FF] font-bold">
            cuotas
          </span>
          <span className="w-full px-4 text-sm font-semibold text-center text-white bg-black rounded-md">
            sin interés
          </span>
        </div>
      </div>
      <div className="flex items-center justify-center h-80 image__container">
        
      <Link to={`product/${id}`} className=" image">
        <img className="w-full h-fit max-h-80" src={pictures[0]} alt={`Image ${name}`} />
      </Link>
      </div>
      <span className="overflow-hidden text-xl font-bold text-ellipsis line-clamp title">
        {name}
      </span>
      <span className="text-sm text-gray-500 subtitle">{code}</span>
      <hr className="w-full mt-4 mb-3 " />
      <div className="flex justify-center gap-6 send__images">
        <img
          src="https://samsungar.vtexassets.com/_v/public/assets/v1/published/samsungbr.samsung-store@1.424.2/public/react/e125a661dee99f25f97aaa312e0dc663.png"
          alt=""
        />
        <img
          src="https://samsungar.vtexassets.com/_v/public/assets/v1/published/samsungbr.samsung-store@1.424.2/public/react/78cf68a962dc9dff8f45eede4e9bbf88.png"
          alt=""
        />
      </div>
      <div onClick={()=> addToCart(id)} className="flex items-center justify-center h-10 mt-4 font-semibold text-white transition-all duration-300 ease-in-out bg-black border-2 border-black cursor-pointer select-none rounded-2xl hover:bg-white hover:text-black buy__button">
        Comprar
      </div>
    </div>
  );
};

export default ProductCardComponent;
