// src/App.tsx
import FooterComponent from "./components/FooterComponent";
import HeaderComponent from "./components/HeaderComponent";
import Main from "./components/Main";

function App() {
  return (
    <div className="App">
      <HeaderComponent/>
      <Main/>
      <FooterComponent/>
    </div>
  );
}

export default App;

// src/App.vue
<script lang="ts">
import HeaderComponent from "./infrastructure/components/HeaderComponent.vue";
import ModalComponent from "./infrastructure/components/ModalComponent.vue";
export default {
  name:'App',
  components:{ HeaderComponent,ModalComponent}
}
</script>

<template>
  
  <ModalComponent  message="Producto agreado exitosamente!" />
  <HeaderComponent />
  <main>
    <router-view />
  </main>
</template>
