// src/components/HeaderComponent.tsx
import { Link } from "react-router-dom";
import Logo from "../assets/logo.svg";
import NavigationComponent from "./Navigation/NavigationComponent";

const HeaderComponent = () => {
  return (
    <div className="w-full h-20 border-b shadow-md header__container">
      <div className="flx justify-between max-w-screen-2xl h-full mx-auto flex items-center px-8 header__content">
        <div className="header__logo">
          <Link to={"/"}>
            <img src={Logo} alt="Logo Samsung shop" />
          </Link>
        </div>
        <NavigationComponent/>
      </div>
    </div>
  );
};

export default HeaderComponent;

// src/infrastructure/components/HeaderComponent.vue
<template>
  <div class="w-full bg-white border-b h-16 header__container">
    <div
      class="max-w-screen-2xl h-full mx-auto px-8 flex justify-between items-center header__content"
    >
      <router-link to="/" class="logo">
        <img src="../../assets/samsung-logo.png" alt="" />
      </router-link>

      <Cart />
    </div>
  </div>
</template>

<script lang="ts">
import Cart from "./Cart/Cart.vue";

export default {
  name: "HeaderComponent",
  components: { Cart },
  setup() {},
};
</script>
