// src/views/DetailProduct.tsx
import { useParams } from "react-router-dom";
import GalleryComponent from "../components/GalleryComponent";

const DetailProduct = () => {
  let params = useParams();
  console.log(params);
  return (
    <div className="w-full detail__product">
      <div className="mx-auto max-w-screen-2xl product__container">
        {/* BANNER  */}
        <div className="flex items-center justify-between h-20 px-4 bg-black ">
          <span className="text-xl font-bold text-white price">
            50" UHD 4K Smart TV AU7000
          </span>

          <div className="flex items-center gap-12 font-bold text-white price__button">
            <span className="text-xl">$ 139.999</span>
            <div className="rounded-3xl text-sm px-5 bg-[#2189ff] hover:bg-[#006bea] flex items-center justify-center h-10 text-white  transition-all duration-300 ease-in-out cursor-pointer select-none button__buy">
              COMPRAR
            </div>
          </div>
        </div>

        <div className="grid w-full grid-cols-2 gap-8 product__main">
          <GalleryComponent />
        </div>
      </div>
    </div>
  );
};

export default DetailProduct;

// src/infrastructure/pages/DetailProduct.vue
<script lang="ts">
import { ref, watchEffect } from "vue";
import { useRoute } from "vue-router";
import { DetailProduct } from "../../domain/models/Product";
import { productService } from "../../domain/services/Product.service";

import SpinComponent from "../components/SpinComponent.vue";
import Gallery from "../components/DetailProduct/Gallery.vue";
import Information from "../components/DetailProduct/Information.vue"

export default {
  name: "DetailProductView",
  components: {
    SpinComponent,
    Gallery,
    Information,
  },

  setup() {
    let Product = ref<DetailProduct>();
    let loading = ref(true);

    const route = useRoute();

    const getProductById = async () => {
      let productId;

      if (Array.isArray(route.params.productId)) {
        productId = route.params.productId[0];
      } else {
        productId = route.params.productId;
      }
      Product.value = await productService.getProductById(productId);
      if (Product.value) {
        loading.value = false;
      }
    };

    watchEffect(async () => {
      await getProductById();
    });

    return {
      Product,
      loading,
    };
  },
};
</script>

<template>
  <div class="w-full p-4 detail__view">
    <SpinComponent v-if="loading" />
    <div
      v-else
      class="mx-auto w-full max-w-screen-2xl grid grid-cols-1 lg:grid-cols-5 gap-16 home__content"
    >
      <div
        class="col-span-full rounded select-none text-white p-4 gap-4 flex flex-col items-center sm:flex-row justify-between bg-black min-h-20 max-w-screen-2xl font-bold banner"
      >
        <span class="text-2xl">
          {{ Product?.name }}
        </span>
        <div
          class="flex w-full sm:w-auto justify-between gap-8 items-center button__buy__price"
        >
          <span class="text-xl"> ${{ Product?.price }} </span>
          <RouterLink
            to="/"
            class="h-10 cursor-pointer rounded-full flex items-center bg-[#2189FF] px-4 buy__button"
          >
            VOLVER
          </RouterLink>
        </div>
      </div>
      <Gallery :fees="Product?.fees" :pictures="Product?.pictures" />
      <Information
        :fees="Product?.fees"
        :code="Product?.code"
        :discount="Product?.discount"
        :id="Product?.id"
        :price="Product?.price"
        :name="Product?.name"
      />
    </div>
  </div>
</template>
